#!/usr/bin/env nu

# Exercise the real PreToolUse entrypoint. Commands are JSON data only:
# never execute any git/forge write appearing in a fixture.
def main [] {
    let root = ($env.FILE_PWD | path dirname)
    let hook = ($root | path join plugins/core/skills/git/hooks/block-attribution.nu)
    if not ($hook | path exists) {
        print -e "FAIL: attribution hook is missing"
        exit 1
    }
    let fixture = (mktemp -d)
    "- Fix login\n\n🤖 Generated with Claude Code\n" | save ($fixture | path join attributed.md)
    "- Update Claude Code documentation\n" | save ($fixture | path join clean.md)
    {body: "Generated with Claude Code"} | to json | save ($fixture | path join payload.json)
    'mutation { addComment(input: {subjectId: "example", body: "Generated with Claude Code"}) { clientMutationId } }' | save ($fixture | path join request.graphql)
    mkdir ($fixture | path join nested)
    "Co-Authored-By: Claude <claude@example.com>" | save ($fixture | path join nested/message.txt)

    let denied = [
        'gh api graphql -F query=@request.graphql'
        'gh pr create --title "fix: hooks" -F attributed.md'
        'gh issue create --title "fix: hooks" -Fattributed.md'
        'gh pr comment 1 -F attributed.md'
        'gh pr review 1 --approve -F attributed.md'
        'gh release create v1 -F attributed.md'
        'git commit -m "fix(core): repair hooks" -m "Generated with Claude Code"'
        'git commit --message="fix(core): repair hooks 🤖"'
        'git commit -m "Co-Authored-By: Claude <claude@example.com>"'
        'git commit -m "Signed-off-by: Agent <agent@example.com>"'
        'git commit -F attributed.md'
        'git commit -t attributed.md'
        'git -C nested commit --file message.txt'
        'git tag -a v1 -m "Generated with Claude Code"'
        'git tag -a v1 -F attributed.md'
        'git branch feature/🤖-cleanup'
        'git checkout -b feature/🤖-cleanup'
        'git switch -c feature/🤖-cleanup'
        'git config branch.feature.description "Generated with Claude Code"'
        'gh pr create --title "fix(core): repair hooks" --body "🤖 Generated with Claude Code"'
        'gh pr edit 1 --body-file attributed.md'
        'gh pr comment 1 --body-file=attributed.md'
        'gh pr review 1 --approve --body "Assisted-by: Claude"'
        'gh issue create --title "🤖 fix hooks" --body "Reproduce failure"'
        'gh issue edit 1 --body "Generated with Claude Code"'
        'gh issue comment 1 --body "Generated by Claude Code"'
        'gh release create v1 --notes "Generated with Claude Code"'
        'gh release edit v1 --notes-file attributed.md'
        'gh repo edit --description "Generated with Claude Code"'
        'gh -R owner/repo pr create --title "fix: hooks" --body-file attributed.md'
        'glab mr create --title "fix: hooks" --description "Generated with Claude Code"'
        'glab mr update 1 --description "🤖 Generated with Claude Code"'
        'glab mr create --title "fix: hooks" --description-file attributed.md'
        'glab mr note create 1 --message "Generated with Claude Code"'
        'glab issue create --title "fix hooks" --description "Generated with Claude Code"'
        'glab issue update 1 --description "Generated with Claude Code"'
        'glab issue note 1 --message "Generated with Claude Code"'
        'glab release create v1 --notes "Generated with Claude Code"'
        'gh api repos/owner/repo/issues -f title="fix hooks" -f body="Generated with Claude Code"'
        'gh api repos/owner/repo/issues/1/comments -F body=@attributed.md'
        'gh api repos/owner/repo/issues/1/comments --input payload.json'
        'glab api projects/1/issues -X POST -f description="Generated with Claude Code"'
        `gh api graphql -f query='mutation { addComment(input: {subjectId: "example", body: "Generated with Claude Code"}) { clientMutationId } }'`
        'gh pr create --title "fix: hooks" --body-file missing.md'
        'git commit -F missing.md'
        'gh pr create --title "fix: hooks" --body-file "$BODY_FILE"'
    ]
    let allowed = [
        'gh pr create --title "fix: hooks" -F clean.md'
        'gh release create v1 -F clean.md'
        'git commit -m "docs(claude-code): update setup instructions"'
        'git commit -F clean.md'
        'git branch feature/claude-code-docs'
        'git branch -t feature origin/main'
        'git push -t origin'
        'git tag -a v1 -m "Claude Code integration"'
        'gh pr create --title "docs: update Claude Code guide" --body-file clean.md'
        'gh issue create --title "Claude Code hook fails" --body "Steps to reproduce"'
        'glab mr create --title "docs: update guide" --description "Document Claude Code installation"'
        'glab mr create --title "docs: update guide" --description-file clean.md'
        'gh issue create --title "Update schema" --body "Generated by [Protobuf](https://protobuf.dev)"'
        'gh issue create --title "Update price" --body "Price is $5"'
        `gh api graphql -f query='query($owner: String!) { repository(owner: $owner, name: "example") { name } }' -f owner=example`
        'gh release create v1 --notes-file clean.md'
        'gh api repos/owner/repo/issues/1/comments -F body=@clean.md'
        'rg "Generated with Claude Code|🤖" plugins'
        'git log --all --grep="Generated with Claude Code"'
        'git grep "Co-Authored-By"'
        'gh pr view 1 --json body --jq ".body | contains(\"Generated with Claude Code\")"'
        'glab issue view 1'
        'printf "%s" "gh pr create --body Generated with Claude Code"'
        'gh pr create --help'
    ]
    mut failures = []
    for group in [{commands: $denied, want: 2} {commands: $allowed, want: 0}] {
        for command in $group.commands {
            let payload = {tool_name: Bash, cwd: $fixture, tool_input: {command: $command}}
            let result = ($payload | to json | ^nu $hook | complete)
            if $result.exit_code != $group.want or ($group.want == 2 and ($result.stderr | str trim | is-empty)) {
                $failures = ($failures | append $"($command): expected ($group.want), got ($result.exit_code); ($result.stderr | str trim)")
            }
        }
    }
    let harmless_payloads = [
        ''
        '{ malformed json'
        '{"tool_name":"Read","tool_input":{"command":"git commit -m 🤖"}}'
        '{"tool_name":"Bash","tool_input":{"command":42}}'
    ]
    for payload in $harmless_payloads {
        let result = ($payload | ^nu $hook | complete)
        if $result.exit_code != 0 or ($result.stderr | str contains 'Error:') {
            $failures = ($failures | append $"Malformed/non-Bash payload failed: ($result.stderr)")
        }
    }
    # Invoke installed hook commands with their actual plugin root, so the
    # all-skills package cannot silently omit the guard or startup policy.
    for plugin_root in [$root ($root | path join plugins/core)] {
        let config = (open ($plugin_root | path join hooks/hooks.json))
        let gates = ($config.hooks.PreToolUse | where matcher == Bash | get hooks | flatten | where command =~ 'block-attribution\.nu')
        let starts = ($config.hooks.SessionStart | get hooks | flatten)
        if ($gates | length) != 1 {
            $failures = ($failures | append $"($plugin_root): expected one Bash attribution hook")
        } else {
            let payload = {tool_name: Bash, cwd: $fixture, tool_input: {command: 'gh issue create --title "test" --body "Generated with Claude Code"'}}
            let result = (with-env {CLAUDE_PLUGIN_ROOT: $plugin_root} {
                $payload | to json | ^bash -c $gates.0.command | complete
            })
            if $result.exit_code != 2 {
                $failures = ($failures | append $"($plugin_root): configured hook did not deny attribution: ($result.stderr)")
            }
        }
        if ($starts | length) != 1 {
            $failures = ($failures | append $"($plugin_root): expected startup policy hook")
        } else {
            let result = (with-env {CLAUDE_PLUGIN_ROOT: $plugin_root} {
                '{}' | ^bash -c $starts.0.command | complete
            })
            if $result.exit_code != 0 or not ($result.stdout | str contains 'NO agent attribution anywhere') {
                $failures = ($failures | append $"($plugin_root): startup hook did not deliver attribution policy")
            }
        }
    }
    rm -rf $fixture
    if not ($failures | is-empty) {
        $failures | each {|failure| print -e $"FAIL: ($failure)" }
        exit 1
    }
    print $"PASS: attribution hook — ($denied | length) denied, ($allowed | length) allowed; fixture commands never executed"
}
